### ISSUE TITLE
curiousapple - Missing checks in 2 places, allows proxy holders to drain the margin account

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-dodo-judging#104]
curiousapple

high

# Missing checks in 2 places, allows proxy holders to drain the margin account

## Summary
Missing checks in 2 places, allows proxy holders to drain the margin account.

## Vulnerability Detail
Dodo defines the proxy role with the following intent 

> Q: Are there any additional protocol roles? If yes, please explain in detail:
> There is a proxy role that has permissions stored in the ALLOWED_FLASH_LOAN structure. This role can execute opening or closing positions on behalf of the user to achieve stop loss or take profit objectives.

**The intent here is that users allow proxy addresses to act on their behalf, to their benefit.**
There are checks in multiple places to enforce above, that beneficiary remains margin account only even if action is being executed by proxy.

For example
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L376
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L365

However, there are two places where checks are missed, exposing funds at proxy's mercy :) 

1. `_swapApproveTarget`
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L308-L310
The proxy holder can pass their own address as `_swapApproveTarget` and get an infinite allowance on user funds.

> Attack: 
> flag: 1 
> _swapApproveToken[]: all tokens margin account holds
> _swapAddress: some dummy contract with fallback
> tradeAssets: empty
> withdrawAssets: empty

2. `_swapAddress`
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L312
This line basically gives complete ad-hoc access to the proxy, using a combination of `_swapAddress` and `_swapParams`, they can basically do anything, eg: transfer tokens, and approve them.....

_Note: This is applicable for both open and close trade_

## Impact
Loss of user funds
The trust assumption of DODO considering proxy access is broken.

## Code Snippet
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L308
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L312

## Tool used
Manual Review

## Recommendation
Consider validating swap parameters

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is not valid M. Authorized proxy is guy you trust. This is your own fault.

**Comment by Shogoki** [comment]
Escalate for 10 USDC

I think i agree with @securitygrid on this specific report, talking about the proxy holders. 
The issue is a bit better stated out in my report here: https://github.com/sherlock-audit/2023-05-dodo-judging/issues/98
Vulnerability is that anybody can call this function and get the tokens approved to himself.

In my opinion this report is not a valid finding, but others (including mine) marked as duplicate, are.
I think there are several duplicates listed here which are talking about different things: 
- Proxy can steal tokens (probably invalid)
- Malicious DoDo approve (probably invalid)
- Anyone (attacker) can steal funds by approving

Goal of this escalation should be to:
- choose a better main report
- Recheck the duplicates

**Comment by ctf-sec** [comment]
Agree with [Shogoki](https://github.com/Shogoki)

https://github.com/sherlock-audit/2023-05-dodo-judging/issues/98

```solidity
        if (_swapParams.length > 0) {
            // approve to swap route
            for (uint256 i = 0; i < _swapApproveToken.length; i++) {
                IERC20(_swapApproveToken[i]).approve(_swapApproveTarget, type(uint256).max);
            }

            (bool success,) = _swapAddress.call(_swapParams);
            require(success, "dodoswap fail");
        }
```

certainly arbitrary approval and arbitrary execution is dangerous 

combing with the fact that the executionOperation does not really check the initiator address, fund can be stolen

Recommend making issue 98 as primary and maintain the severity

**Comment by securitygrid** [comment]
#98 is same as #69. #69 was classified as a duplicate of #34. Please review it.

**Comment by ctf-sec** [comment]
Recommend making 98 duplicate of both 104 and 34, and making 69 duplicate of both 104 and 34 as well

**Comment by sashik-eth** [comment]
@ctf-sec Please check #45, it also mentions constructing arbitrary parameters for `swapAddress` that allows the transfer of tokens to the attacker address.

**Comment by abhishekvispute** [comment]
> Escalate for 10 USDC
> 
> I think i agree with @securitygrid on this specific report, talking about the proxy holders. The issue is a bit better stated out in my report here: #98 Vulnerability is that anybody can call this function and get the tokens approved to himself.
> 
> In my opinion this report is not a valid finding, but others (including mine) marked as duplicate, are. I think there are several duplicates listed here which are talking about different things:
> 
> * Proxy can steal tokens (probably invalid)
> * Malicious DoDo approve (probably invalid)
> * Anyone (attacker) can steal funds by approving
> 
> Goal of this escalation should be to:
> 
> * choose a better main report
> * Recheck the duplicates

Escalate for 10 USDC

Hey,  
Clearing some facts since I was the author of this issue
All confusion is due to the wrong assignment for duplicates (cc: @ctf-sec )
This issue does not talk about the flash loan callback attack vector
I had a separate issue with it https://github.com/sherlock-audit/2023-05-dodo-judging/issues/93
The issue of anyone stealing tokens by infinite approval of flash loan callback is a different issue and should be handled as a duplicate of #34 @Shogoki 

This issue talks about breaking protocols assumption with respect to allowed proxies.
As I mentioned in the issue as well, DODO mentions that account holders are allowed to proxy to do actions on their behalf in their interest.

![image](https://github.com/sherlock-audit/2023-05-dodo-judging/assets/46760063/90c49d40-3fd3-4a10-b165-726a90b9a249)
 
"Their interest" is key here, DODO at multiple places has added checks to insure that beneficiary remains the account holder only to enforce it. (please check the issue for more details)
However, they missed doing so at the two places I mentioned which allows more privileges than intended.

Considering that DODO defines the allowed proxy role clearly, and even has incomplete checks inside their code, to protect account holders against it, I think this issue should be considered valid.

**Comment by Shogoki** [comment]
In my opinion they are different issues #98 is about the infinite approval to `swapApproveToken`. 
it is different from letting an attacker call arbitrary contracts (#96)

**Comment by abhishekvispute** [comment]
Hmm, I think both of #98 and #96 are same
The cause for both of the issues is not checking the flash loan initiator, right?
As per as I know, Issue is grouped by cause, while impacts could be different 

For example for my report of this flash loan callback issue, I report both arbitrary address and infinite approval in one issue only 
#93 
![image](https://github.com/sherlock-audit/2023-05-dodo-judging/assets/46760063/2424021c-5f72-4ddd-a99e-7f3c053580bf)

**Comment by Shogoki** [comment]
Hmm.
Is this practice stated anywhere in the docs? 
Because it is 2 different attack vectors. 
Each one requires 2 bugs to be vulnerable, where only the first one (missing initiator check) is the same.

**Comment by ChmielewskiKamil** [comment]
I am with @abhishekvispute on this one. In the judging contest, I had a problem with #96 and #98 since they are both good reports, but I do think that they are almost the same. 

I also think that #104 should be a separate issue because it mentions different impact and different attack vector than other highs.

**Comment by roguereddwarf** [comment]
@ChmielewskiKamil 
I don't think this issue should be a separate High.
Other issues like #29 describe the exact same root cause with `_swapAddress` and `_swapApproveTarget`.

It is usually the case with different reports that they have a slightly different take on a vulnerability.
What's important here is that the proxy has the ability to steal funds and cause other high risk impact due to missing validations on the addresses that the proxy can pass.

It would be another story if this issue was the only one that captures the "High" impact with the other ones only capturing a "Medium" impact.

**Comment by ctf-sec** [comment]
Can consider this as a duplicate of https://github.com/sherlock-audit/2023-05-dodo-judging/issues/34

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
After further review considering this issue and some of its duplicates low for the following reasons:
The proxy address is set by the user, and the damage is to the user themselves. 
The role of the proxy is defined however there are no restrictions mentioned and such cases the Sponsor opinion is considered in terms of trust assumptions of these roles. 
Some of the duplicates in the above issue are duplicates of #34
