### ISSUE TITLE
roguereddwarf - MarginTrading.sol: Attacker can manipulate DODO trading pairs such that margin trades cannot be closed

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-dodo-judging#138]
roguereddwarf

medium

# MarginTrading.sol: Attacker can manipulate DODO trading pairs such that margin trades cannot be closed

## Summary
The DODO Margin Trading protocol integrates with the core DODO protocol to perform swaps.
Swaps are needed to open and close margin trades.

The intended tokens to be used are the following:
![2023-05-12_13-24](https://github.com/sherlock-audit/2023-05-dodo-roguereddwarf/assets/118631472/56e4dd9f-1fb6-4d34-948e-c14b33aa856b)

The issue is that these swap pairs are not liquid. Some of them have a TVL of 0:
https://info.dodoex.io/all
![2023-05-12_13-26](https://github.com/sherlock-audit/2023-05-dodo-roguereddwarf/assets/118631472/3d1c52ab-d3b6-4b46-8af2-dd8e68f29a01)

One might think that this is an issue due to potential slippage. This is true but it's not the main concern here. The user can specify a minimum output amount for the DODO swap.

However there is another issue related to this.

## Vulnerability Detail
An attacker might provide liquidity to an illiquid swap pair such that users can open margin trading positions:
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L257-L279

When the attacker then withdraws his liquidity the users cannot close their margin trading positions anymore since closing a trade does also require a swap:
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L294-L356

## Impact
The slippage is one concern. The bigger concern is that the attacker can manipulate swap pairs such that margin trades cannot be closed anymore and users incur losses in their trades without being able to close them.

## Code Snippet
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L257-L279

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L294-L356

## Tool used
Manual Review

## Recommendation
Only allow those margin trades to be opened such that the corresponding swap pairs have sufficient liquidity. Sufficient liquidity means that the swap pair cannot be manipulated by an attacker.

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is valid low/info as stated by the sponsor. No bad impact.

**Comment by ctf-sec** [comment]
The impact is 

> The slippage is one concern. The bigger concern is that the attacker can manipulate swap pairs such that margin trades cannot be closed anymore and users incur losses in their trades without being able to close them

because when liquidity is poor, price manipulation is easy,

intend to maintain issue's severity level

**Comment by securitygrid** [comment]
in readme:
### Q: Which ERC20 tokens do you expect will interact with the smart contracts? 
WETH USDC WBTC DAI MATIC
Where does the illliquid swap pair come from?

The slippage is one concern.
Will the offline parameter _swapParams have no slippage protection?

**Comment by roguereddwarf** [comment]
You can check out all trading pairs here: https://info.dodoex.io/all

Affected pairs are e.g. WMATIC - DAI
![2023-05-27_13-42](https://github.com/sherlock-audit/2023-05-dodo-judging/assets/118631472/7569ac2c-496b-4442-b479-7ce660717622)

**Comment by securitygrid** [comment]
Agreed. But I don't want to close it. Please let sherlock know my 5 questions.
@roguereddwarf：
I can't see the screenshots in your report.

**Comment by roguereddwarf** [comment]
Yeah it was a mistake on my end so I commented the screenshot above (accidentally had the old screenshots in a private repo)

**Comment by Zack995** [comment]
DODO itself is an aggregator, and all trades are evaluated. If the liquidity is insufficient, it will utilize external pools, so trading issues won't arise due to DODO's liquidity unless the supported DEX or aggregator on that chain fails to provide liquidity.

**Comment by abhishekvispute** [comment]
Escalate for 10 USDC

The attack vector mentioned here is 
"the attacker adds liquidity to dodo pools and allows the user to open a position, but later removes it to stop the user from closing them"
:red_circle:  **This is a wrong assumption** :red_circle: 
The concerned liquidity being mentioned is about dodo pools, however, the user is not limited to using the liquidity from dodo pools only.

Even if someone removes all liquidity from Dodo, there are 2 ways users can close their positions.

**Way 1** :green_circle: 
Procure the assets externally from other liquid pools (uniswap, sushiswap...), transfer them to the margin account, and execute `_closeTrade` by passing swapParams as empty bytes.
hence the swap on dodo would be skipped by this check 
https://github.com/sherlock-audit/2023-05-dodo/blob/930565dd875dac24609441423c7c76c2ae4719a8/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L306

and by following the line balance of the token would be used 
https://github.com/sherlock-audit/2023-05-dodo/blob/930565dd875dac24609441423c7c76c2ae4719a8/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L322
Allowing users to close their trade

**Way 2** :green_circle: 
See, there is no enforcement inside margin accounts that the swap address needs to be the dodo router address only, even the interface is not locked due to the low-level call.
So one can pass liquid uniswap or any pool's address and execute a swap

tokens are approved here: https://github.com/sherlock-audit/2023-05-dodo/blob/930565dd875dac24609441423c7c76c2ae4719a8/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L309
swap is done here
https://github.com/sherlock-audit/2023-05-dodo/blob/930565dd875dac24609441423c7c76c2ae4719a8/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L312

**Comment by roguereddwarf** [comment]
Upon seeing the escalations I think this is not a valid H/M

**Comment by ctf-sec** [comment]
> Upon seeing the escalations I think this is not a valid H/M

Agree

**Comment by hrishibhat** [comment]
Result:
Invalid
Has duplicates
Based on the above escalation considering this a non-issue
