### ISSUE TITLE
BAHOZ - Account type of MarginTrade contract has no effects on the account

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-dodo-judging#71]
BAHOZ

medium

# Account type of MarginTrade contract has no effects on the account

## Summary

Account type of MarginTrade contract -cross vs isolated- has no actual effect on the account and this may cause all feature deposits to be blocked by Aave

## Vulnerability Detail

In cross margin accounts, all open positions use the same margin balance and liquidation of one position may affect other positions. They are suitable for traders with multiple positions on margin.

In isolated margin accounts, each open positions has their own margin and they can be separately managed. They are suitable for speculative and highly leveraged positions.

`Aave` uses isolation mode as follows:

> Isolation mode allows to list new assets as Isolated which has a specific debt ceiling and can be only used to borrow stablecoins that have been permitted, by `Aave` Governance, to be borrowable in isolation mode.

https://docs.aave.com/developers/whats-new/isolation-mode

Depending on `Aave`s docs, isolated accounts are supposed to be used to handle isolated assets only. However account mode is never passed from factory contract to the MarginTrading contract and it is only stored in the factory contract without any effects apart from keeping the count of the different type of margin accounts in `isolatedMarginTrading` and `crossMarginTrading` variables.

There is also no checks in the `MarginTrading.sol` contract that assures a cross mode borrower does not use an isolated asset as collateral and same is missing for isolation mode accounts.

Check `Aave`s docs https://docs.aave.com/developers/whats-new/isolation-mode:

> In case the user has other assets enabled as collateral, they can still supply Isolated Asset to capture the yield but won’t be able to use it as collateral

> Borrower in Isolation Mode cannot enable any other assets including the other isolated assets as collateral.

This will allow users to create any type of accounts in factory and then proceed to deposit the wrong type of asset to lendingPool. 

Consider this case:
A user creates a cross margin account calling `createMarginTrading()` with `_flag = 1`. Then deposit an isolated asset to the margin trading account as first deposit. Although the account type is cross margin account, `Aave` will consider this account as isolated from now on. This will cause adding a new asset as collateral to be reverted by `Aave`.

## Impact

Wrong account type, deposits to `Aave` may be blocked, discrepency between account types in `Aave` and `Dodo`

## Code Snippet

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L120-L127

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L128-L135

## Tool used

Manual Review

## Recommendation

Store account type flag in `initialize()` of `MarginTradin.sol` and require deposits to cross margin accounts to be unisolated asset and deposits to isolated margin account are isolated assets.

**Comment by 8ahoz** [comment]
Escalate for 10 USDC

I think the issue is valid, accounts will be registered wrongly in the factory and there is a real possibility of Aave deposits getting blocked unexpectedly. Please explain your reasoning to exclude this issue and re-evaluate your decision. Happy to answer any questions.

**Comment by roguereddwarf** [comment]
I think the issue is correctly marked as Non-Reward because
1) The watson points to documentation of Aave V3's isolation mode when it has been made clear by the sponsor that the protocol integrates with Aave V2 instead (which has no isolation mode)

I think the mistake in 1) has mislead the Watson in his thinking what the `_flag` parameter actually is.

2) In reality it's only a self-reported flag that the user can set for how he intends to use a specific
`MarginTrading` instance.

This self-reported flag could then be used by a front-end to represent the `MarginTrading` accounts in different ways (e.g. offer different actions).

Setting the `_flag` to one margin mode but using it as another margin mode is a user error and does not have any impact because the contract logic is exactly the same.

I.e. the user is fully in control of the flash loans he performs and thereby positions he takes on.

**Comment by 8ahoz** [comment]
@roguereddwarf Can you point me where in docs they mention the protocol supposed to use only v2?
Having both MockLendingPoolV3 and MockLendingPoolV2 in the repo makes me think they were planning to use both.

**Comment by roguereddwarf** [comment]
They mentioned this in the Discord: https://discord.com/channels/812037309376495636/1105509498145222707/1106089796595621918

But regardless of whether they use Aave V3 or Aave V2, the entries ìn `crossMarginTrading` and `isolatedMarginTrading` are only for "view" purposes.
There is no different behavior associated with either.

The notion of `crossMarginTrading` and `isolatedMarginTrading` is only self-reported by the user and there is no connection with Aave V2 isolation mode.

**Comment by 8ahoz** [comment]
I agree they are not used for anything else than reporting and thats the reason why I raised the issue. They should be used to block certain deposits that will change the account type. Crossmargin accounts should block isolated deposits and vice versa.

If there is a view only variable that reports wrong info than I believe thats not something we should disregard as we don't know how that view only function will be used. If those values are not reporting the account type correctly, then I would argue they should be removed from the contract because they are causing a good deal of confusion. 

Thanks for sharing the discord message, but I used docs and the repo as source of truth and they are telling me the project will be using both v3 and v2 (MockLendingPoolV3)

I appreciate the discussion, and I believe it will serve well when making the final decision.
